### ISSUE TITLE
Lower Result

### ISSUE THREAD

**Issue by dyahayumgw** [lzcn/LPAE-Net#3]
Hi,

I run the code using the original config file. However, I got lower results compared to the paper. Anybody knows why?

I run it twice:

AUC : 0.7261 | NDCG: 0.6661
AUC : 0.7307 | NDCG: 0.6705

Thanks.

**Comment by lzcn** [comment]
> Hi,
> 
> I run the code using the original config file. However, I got lower results compared to the paper. Anybody knows why?
> 
> I run it twice:
> 
> AUC : 0.7261 | NDCG: 0.6661 AUC : 0.7307 | NDCG: 0.6705
> 
> Thanks.

In default settings, I wrongly use the outfits generated for the FTIB task to evaluate the AUC. Thus, the performance is much lower. To get the correct results, you can simply comment out the corresponding code block.
